"""API-mode client for ctrip hotel crawl.

Architecture (validated 2026-08):
- Hotel LIST: pure HTTP via curl_cffi (no browser, no anti-bot) — uses SOA2 `fetchHotelList`.
- Hotel ROOM STATUS: the SOA2 `getHotelRoomListInland` endpoint is gated by a dynamic
  `phantom-token` header that is generated by the page JS (`window.signature`) and is
  bound to the first request's hotel. It CANNOT be replayed cross-hotel with pure HTTP.

  Working approach: keep ONE headless browser page, navigate it once to any hotel detail
  page so the page JS produces a valid phantom-token, capture the full request template
  (URL + POST body) that the page fires, then replay it from *inside* the page context via
  `page.evaluate(fetch(...))`, changing only `search.hotelId` per hotel. The browser JS
  regenerates the token per request, so it works for every hotel. Measured ~0.8s/hotel,
  100% success serially. Concurrent Promise.all triggers anti-bot and returns empty —
  so requests MUST be serial per browser instance.

  Multiple browser instances (config `api_workers`) can run in parallel, each with its own
  page, to scale throughput without concurrent races inside a single page.
"""

from __future__ import annotations

import json
import threading
import time
from pathlib import Path
from typing import Any

from curl_cffi import requests as cffi_requests

from ctrip_hotel.config import ROOT

# ---------------------------------------------------------------------------
# Hotel list — pure HTTP (no browser needed)
# ---------------------------------------------------------------------------

_LIST_URL = "https://m.ctrip.com/restapi/soa2/31454/fetchHotelList"
_ROOM_URL = "https://m.ctrip.com/restapi/soa2/33278/getHotelRoomListInland"


def extract_proxy_pool(cfg: dict[str, Any]) -> list[str]:
    """Build a list of proxy URLs from config.

    Sources (first non-empty wins):
      1. `proxy_list` (list of "ip:port" / "http://ip:port")
      2. `proxy` (single)
      3. `proxy_api_url` — a JSON API that returns {"obj": [{"ip":..,"port":..}]}
    """
    out: list[str] = []
    for p in cfg.get("proxy_list") or []:
        s = str(p).strip()
        if s and s not in out:
            out.append(s if "://" in s else f"http://{s}")
    single = cfg.get("proxy")
    if single:
        s = str(single).strip()
        if s and s not in out:
            out.append(s if "://" in s else f"http://{s}")
    api_url = cfg.get("proxy_api_url")
    if api_url and not out:
        try:
            import urllib.request
            raw = urllib.request.urlopen(str(api_url), timeout=15).read()
            data = json.loads(raw)
            for item in data.get("obj") or []:
                ip, port = item.get("ip"), item.get("port")
                if ip and port:
                    u = f"http://{ip}:{port}"
                    if u not in out:
                        out.append(u)
        except Exception as e:
            print(f"  [proxy] 提取代理失败: {e}")
    return out

MOBILE_UA = (
    "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1"
)

_LIST_HEAD = {
    "platform": "H5",
    "group": "ctrip",
    "cid": "hotel",
    "ctok": "",
    "cver": "1.0",
    "lang": "01",
    "sid": "0000",
    "syscode": "09",
    "auth": "",
    "extension": [],
}


def fetch_hotel_list_pure(
    *,
    city_id: int,
    check_in: str,
    check_out: str,
    pages: int = 1,
    page_size: int = 20,
    delay_ms: int = 0,
    on_page: Any = None,
    proxy: str | None = None,
    proxies: list[str] | None = None,
) -> list[dict[str, Any]]:
    """Fetch hotel catalog via pure HTTP (curl_cffi impersonate=chrome).

    `proxy` is a single proxy URL like "http://ip:port".
    `proxies` is a list of proxy URLs; requests rotate through them per page.
    """
    headers = {
        "User-Agent": MOBILE_UA,
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "zh-CN,zh;q=0.9",
        "Content-Type": "application/json",
        "Referer": "https://m.ctrip.com/webapp/hotel/hotellist",
        "Origin": "https://m.ctrip.com",
    }
    proxy_pool = list(proxies or [])
    if proxy:
        proxy_pool.append(proxy)
    all_items: list[dict[str, Any]] = []
    for page_idx in range(1, int(pages or 1) + 1):
        body = {
            "head": _LIST_HEAD,
            "destination": {"type": 2, "geo": {"cityId": int(city_id)}},
            "checkIn": check_in,
            "checkOut": check_out,
            "paging": {"pageIndex": page_idx, "pageSize": int(page_size)},
        }
        proxy_url = proxy_pool[(page_idx - 1) % len(proxy_pool)] if proxy_pool else None
        try:
            kwargs: dict[str, Any] = {"impersonate": "chrome", "timeout": 20}
            if proxy_url:
                kwargs["proxies"] = {"http": proxy_url, "https": proxy_url}
            r = cffi_requests.post(_LIST_URL, json=body, headers=headers, **kwargs)
            j = r.json()
        except Exception as e:
            print(f"  [list] page {page_idx} error: {e}")
            break
        data = j.get("data") or {}
        items = data.get("hotelList") or []
        if not items:
            break
        all_items.extend(items)
        if on_page:
            on_page(items, page_idx)
        if page_idx < int(pages or 1) and delay_ms:
            time.sleep(delay_ms / 1000.0)
        # Ctrip caps pageSize ~20; stop if fewer than requested (last page).
        if len(items) < int(page_size):
            break
    return all_items


# ---------------------------------------------------------------------------
# Room status — single headless browser page + in-page fetch replay
# ---------------------------------------------------------------------------

_ROOM_TEMPLATE_SCRIPT = """
() => {
  const tpl = window.__CTRIP_ROOM_TEMPLATE__;
  if (!tpl) return null;
  return {
    url: tpl.url,
    post: tpl.post,
    hasTemplate: true,
  };
}
"""

_FETCH_ROOM_SCRIPT = """
async (args) => {
  const {url, post, hotelId} = args;
  const resp = await fetch(url, {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: post,
    credentials: 'include',
  });
  const j = await resp.json();
  return j;
}
"""


class ApiRoomClient:
    """One headless browser page that produces valid phantom-tokens.

    Use `fetch_room(hotel_id)` repeatedly (serial) to get full room status.
    """

    def __init__(
        self,
        cfg: dict[str, Any],
        *,
        worker_id: int | None = None,
        seed_hotel_id: int | str | None = None,
    ) -> None:
        self.cfg = cfg
        self.worker_id = worker_id
        self.seed_hotel_id = seed_hotel_id
        self._pw = None
        self._browser = None
        self._page = None
        self._template: dict[str, Any] | None = None
        self._album_template: dict[str, Any] | None = None
        self._additional_template: dict[str, Any] | None = None
        self._cookies: str = ""

    # -- lifecycle ---------------------------------------------------------

    def __enter__(self) -> "ApiRoomClient":
        from playwright.sync_api import sync_playwright

        self._pw = sync_playwright().start()
        # API mode is headless by default; set api_headed=true (or pass
        # --headed) only to manually pass a one-time captcha during warmup.
        headed = bool(self.cfg.get("api_headed", self.cfg.get("headed", False)))
        launch_kwargs: dict[str, Any] = {
            "headless": not headed,
            "args": ["--disable-dev-shm-usage"],
        }
        channel = (self.cfg.get("browser_channel") or "").lower()
        if channel in {"msedge", "chrome"}:
            try:
                self._browser = self._pw.chromium.launch(
                    channel=channel, **launch_kwargs
                )
            except Exception:
                self._browser = self._pw.chromium.launch(**launch_kwargs)
        else:
            self._browser = self._pw.chromium.launch(**launch_kwargs)
        context_kwargs: dict[str, Any] = {"locale": "zh-CN"}
        proxy = self.cfg.get("proxy") or self.cfg.get("browser_proxy")
        if proxy:
            context_kwargs["proxy"] = {"server": str(proxy)}
        ctx = self._browser.new_context(**context_kwargs)
        self._page = ctx.new_page()
        self._page.add_init_script(
            """
            Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
            window.chrome = window.chrome || { runtime: {} };
            """
        )
        self._warmup()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        try:
            if self._browser:
                self._browser.close()
        except Exception:
            pass
        try:
            if self._pw:
                self._pw.stop()
        except Exception:
            pass

    # -- warmup ------------------------------------------------------------

    def _warmup(self) -> None:
        """Navigate to a hotel detail page so the page JS emits a room request.

        We capture the request (URL + POST body) that the page fires, and stash it
        on window.__CTRIP_ROOM_TEMPLATE__ for reuse.
        """
        assert self._page is not None
        seed = self.seed_hotel_id
        if seed is None:
            seed = int(self.cfg.get("seed_hotel_id") or 0) or 1
        # Try a few seed hotels in case the page does not fire the room API
        # (anti-bot can be flaky). Reuses the same page across attempts.
        seed_ids = [seed]
        extras = self.cfg.get("seed_hotel_ids") or []
        seed_ids.extend(int(x) for x in extras if str(x).isdigit())

        captured: dict[str, Any] = {}

        # Capture via a fetch hook injected before page load — more reliable than
        # the page.on("request") event, and lets us grab the phantom-token header
        # that the page automatically attaches.
        self._page.add_init_script(
            """
            window.__CTRIP_CAPTURED__ = window.__CTRIP_CAPTURED__ || {};
            const origFetch = window.fetch;
            window.fetch = function(...args) {
                try {
                    const [url, opts] = args;
                    const u = String(url);
                    if (u.includes('getHotelRoomListInland')) {
                        window.__CTRIP_CAPTURED__.room = {
                            url: u,
                            post: opts ? String(opts.body || '') : '',
                            headers: opts && opts.headers ? JSON.parse(JSON.stringify(opts.headers)) : {}
                        };
                    } else if (u.includes('gethotelalbumpicture') || u.includes('ctgethotelalbum')) {
                        if (!window.__CTRIP_CAPTURED__.album) {
                            window.__CTRIP_CAPTURED__.album = {url: u, post: opts ? String(opts.body || '') : ''};
                        }
                    } else if (u.includes('getdetailadditionalinfo')) {
                        if (!window.__CTRIP_CAPTURED__.additional) {
                            window.__CTRIP_CAPTURED__.additional = {url: u, post: opts ? String(opts.body || '') : ''};
                        }
                    }
                } catch(e) {}
                return origFetch.apply(this, args);
            };
            """
        )
        for i, sid in enumerate(seed_ids):
            url = (
                f"https://m.ctrip.com/webapp/hotel/hoteldetail/{sid}.html"
                f"?checkIn={self.cfg['check_in']}&checkOut={self.cfg['check_out']}"
            )
            print(f"  [api] warmup attempt {i + 1}/{len(seed_ids)}: seed={sid}")
            self._page.evaluate("() => { window.__CTRIP_CAPTURED__ = {}; }")
            try:
                self._page.goto(url, timeout=60000)
            except Exception as e:
                print(f"  [warmup] goto warning: {e}")
            # Wait for the room API to fire; scroll to trigger album/additional.
            deadline = time.time() + 15
            while time.time() < deadline:
                cap = self._page.evaluate("() => window.__CTRIP_CAPTURED__ || {}")
                if cap.get("room"):
                    captured["room"] = cap["room"]
                    if cap.get("album"):
                        captured["album"] = cap["album"]
                    if cap.get("additional"):
                        captured["additional"] = cap["additional"]
                    break
                self._page.wait_for_timeout(400)
                if time.time() < deadline:
                    try:
                        self._page.mouse.wheel(0, 1200)
                    except Exception:
                        pass
            if "room" in captured:
                break

        if "room" not in captured:
            raise RuntimeError(
                "warmup failed: 未捕获到房态请求模板。常见原因：当前网络/IP 触发临时风控。"
                "可稍等几分钟重试，或设置 headed=true 手动打开窗口过一次人机验证，"
                "或换 seed_hotel_id / seed_hotel_ids。"
            )
        # Stash templates on window for later evaluate() calls.
        self._page.evaluate(
            """(tpl) => { window.__CTRIP_ROOM_TEMPLATE__ = tpl; }""",
            {"url": captured["room"]["url"], "post": captured["room"]["post"]},
        )
        self._template = captured["room"]
        self._album_template = captured.get("album")
        self._additional_template = captured.get("additional")
        # Capture cookies from the browser context for pure-HTTP replays.
        try:
            self._cookies = "; ".join(
                f"{c['name']}={c['value']}" for c in self._page.context.cookies()
            )
        except Exception:
            self._cookies = ""
        print(
            f"  [api] warmup ok: room={'Y' if self._template else 'N'} "
            f"album={'Y' if self._album_template else 'N'} "
            f"additional={'Y' if self._additional_template else 'N'}"
        )

    # -- room fetch (pure HTTP, token reuse) --------------------------------

    def _room_headers(self) -> dict[str, str]:
        """Build headers for pure-HTTP room requests from the captured template."""
        hdrs = self._template.get("headers") or {}
        base = {
            "User-Agent": hdrs.get("user-agent")
            or "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15",
            "Accept": "application/json, text/plain, */*",
            "Accept-Language": "zh-CN,zh;q=0.9",
            "Content-Type": "application/json",
            "Referer": hdrs.get("referer") or "https://m.ctrip.com/webapp/hotel/hoteldetail",
            "Origin": "https://m.ctrip.com",
            "phantom-token": hdrs.get("phantom-token") or "",
            "cookie": self._cookies or "",
        }
        # Carry the anti-bot context headers that the page sets.
        for k in (
            "x-ctx-wclient-req",
            "x-ctx-ubt-pageid",
            "x-ctx-ubt-vid",
            "x-ctx-ubt-sid",
            "x-ctx-ubt-pvid",
            "cookieorigin",
            "w-payload-source",
        ):
            v = hdrs.get(k)
            if v:
                base[k] = v
        return base

    def fetch_room(self, hotel_id: int | str) -> dict[str, Any]:
        """Fetch full room status for one hotel via pure HTTP (token reuse)."""
        assert self._template is not None, "client not warmed up"
        try:
            body = json.loads(self._template["post"])
            body["search"]["hotelId"] = int(hotel_id)
        except Exception:
            body = {"search": {"hotelId": int(hotel_id)}}
        try:
            r = cffi_requests.post(
                self._template["url"],
                json=body,
                headers=self._room_headers(),
                impersonate="chrome",
                timeout=20,
            )
            j = r.json()
        except Exception as e:
            return {"error": str(e), "data": {}}
        if not isinstance(j, dict):
            return {"error": "non-json response", "data": {}}
        return j

    def fetch_room_batch(
        self,
        hotel_ids: list[int | str],
        *,
        max_workers: int = 8,
    ) -> list[dict[str, Any]]:
        """Fetch rooms for many hotels with a thread pool (pure HTTP)."""
        if max_workers <= 1:
            out = []
            for hid in hotel_ids:
                try:
                    out.append(self.fetch_room(hid))
                except Exception as e:
                    out.append({"error": str(e), "data": {}})
                time.sleep(float(self.cfg.get("delay_ms") or 0) / 1000.0)
            return out
        from concurrent.futures import ThreadPoolExecutor, as_completed

        results: dict[int | str, dict[str, Any]] = {}
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            futs = {ex.submit(self.fetch_room, hid): hid for hid in hotel_ids}
            for fut in as_completed(futs):
                hid = futs[fut]
                try:
                    results[hid] = fut.result()
                except Exception as e:
                    results[hid] = {"error": str(e), "data": {}}
        return [results[hid] for hid in hotel_ids]

    # -- album / additional -------------------------------------------------

    def fetch_album(self, hotel_id: int | str) -> dict[str, Any]:
        """Fetch hotel gallery album via in-page fetch replay."""
        assert self._page is not None
        if not self._album_template:
            return {}
        return self._replay("album", self._album_template, hotel_id)

    def fetch_additional(self, hotel_id: int | str) -> dict[str, Any]:
        """Fetch hotel POI / nearby / tips via in-page fetch replay."""
        assert self._page is not None
        if not self._additional_template:
            return {}
        return self._replay("additional", self._additional_template, hotel_id)

    def _replay(
        self,
        kind: str,
        template: dict[str, Any],
        hotel_id: int | str,
    ) -> dict[str, Any]:
        """Replay a captured request inside the page, changing only hotelId."""
        post = template["post"]
        try:
            body = json.loads(post)
            if kind == "album":
                if "HotelID" in body:
                    body["HotelID"] = int(hotel_id)
                elif "hotelId" in body:
                    body["hotelId"] = int(hotel_id)
            elif kind == "additional":
                if body.get("queryInfo") is not None:
                    body["queryInfo"]["hotelId"] = int(hotel_id)
            payload = json.dumps(body)
        except Exception:
            payload = post
        try:
            j = self._page.evaluate(
                """async (args) => {
                    const resp = await fetch(args.url, {
                        method: 'POST',
                        headers: {'Content-Type': 'application/json'},
                        body: args.post,
                        credentials: 'include',
                    });
                    try { return await resp.json(); }
                    catch(e) { return {error: String(e)}; }
                }""",
                {"url": template["url"], "post": payload},
            )
        except Exception as e:
            return {"error": str(e)}
        return j if isinstance(j, dict) else {}


def normalize_list_payloads(
    items: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Convert raw hotelList items into the catalog shape the rest of the code uses.

    Mirrors `normalize_hotels_from_list_api` but works directly on the raw items.
    """
    rows: list[dict[str, Any]] = []
    for item in items:
        info = item.get("hotelInfo") or item
        summary = info.get("summary") or {}
        name_info = info.get("nameInfo") or {}
        star = info.get("hotelStar") or {}
        comment = info.get("commentInfo") or {}
        position = info.get("positionInfo") or {}
        hotel_id = summary.get("hotelId") or info.get("hotelId")
        if not hotel_id:
            continue
        rows.append(
            {
                "hotel_id": hotel_id,
                "name": name_info.get("name") or info.get("name"),
                "en_name": name_info.get("enName"),
                "star": star.get("star"),
                "score": comment.get("commentScore"),
                "comment_count": comment.get("commenterNumber")
                or comment.get("commentCount"),
                "address": position.get("address") or position.get("positionDesc"),
                "zone": position.get("zoneNames") or position.get("areaName"),
            }
        )
    return rows


def images_from_album_picture(album_payload: dict[str, Any]) -> list[str]:
    """Extract image URLs from the `getHotelAlbumPicture` response.

    Structure: data.AlbumCategoryList[].PictureCategoryList[].AlbumPictureList[]
    Each picture has SmallUrl / LargeUrl / OtherUrl.
    """
    if not album_payload:
        return []
    data = album_payload.get("data") or album_payload
    urls: list[str] = []
    seen: set[str] = set()
    for cat in data.get("AlbumCategoryList") or []:
        if not isinstance(cat, dict):
            continue
        for pcat in cat.get("PictureCategoryList") or []:
            if not isinstance(pcat, dict):
                continue
            for pic in pcat.get("AlbumPictureList") or []:
                if not isinstance(pic, dict):
                    continue
                u = (
                    pic.get("LargeUrl")
                    or pic.get("OtherUrl")
                    or pic.get("SmallUrl")
                    or pic.get("NewSmallUrl")
                )
                if u and isinstance(u, str) and u not in seen:
                    seen.add(u)
                    urls.append(u)
                if len(urls) >= 60:
                    break
            if len(urls) >= 60:
                break
        if len(urls) >= 60:
            break
    return urls


def adapt_album_to_legacy(album_payload: dict[str, Any]) -> dict[str, Any]:
    """Wrap getHotelAlbumPicture response into the legacy `hotelTopImage.imgUrlList`
    shape that `normalize.images_from_album` understands."""
    if not album_payload:
        return {}
    urls = images_from_album_picture(album_payload)
    return {
        "data": {
            "hotelTopImage": {
                "total": len(urls),
                "imgUrlList": [{"imgUrl": u} for u in urls],
            }
        }
    }


def build_fetch_result(
    *,
    hotel_id: int | str,
    hotel_meta: dict[str, Any],
    room_payload: dict[str, Any] | None,
    album_payload: dict[str, Any] | None,
    additional_payload: dict[str, Any] | None,
    check_in: str,
    check_out: str,
) -> dict[str, Any]:
    """Assemble an API-mode fetch result compatible with `build_hotel_document`.

    - `api`: the raw getHotelRoomListInland response (source = "api")
    - `album`: adapted to legacy shape
    - `additional`: raw getDetailAdditionalInfo response
    - `page_hotel`: minimal static info from the list meta (name/star/score/address)
    """
    data = (room_payload or {}).get("data") or {}
    source = "api" if data.get("physicRoomMap") else "none"
    page_hotel = {
        "hotel_id": hotel_id,
        "name": hotel_meta.get("name"),
        "star": hotel_meta.get("star"),
        "address": hotel_meta.get("address"),
        "score": hotel_meta.get("score"),
        "review_count": hotel_meta.get("comment_count"),
        "images": [],
    }
    return {
        "source": source,
        "hotel_id": hotel_id,
        "page_hotel": page_hotel,
        "dom_rooms": [],
        "room_detail_extras": [],
        "api": room_payload,
        "album": adapt_album_to_legacy(album_payload),
        "additional": additional_payload,
        "check_in": check_in,
        "check_out": check_out,
    }
