"""API-mode client for ctrip hotel crawl.

Architecture (validated 2026-08):
- Hotel LIST: pure HTTP via curl_cffi (no browser, no anti-bot) — uses SOA2 `fetchHotelList`.
- Hotel ROOM STATUS: the SOA2 `getHotelRoomListInland` endpoint is gated by a dynamic
  `phantom-token` header that is generated by the page JS (`window.signature`) and is
  bound to the first request's hotel. It CANNOT be replayed cross-hotel with pure HTTP.

  Working approach: keep ONE headless browser page, navigate it once to any hotel detail
  page so the page JS produces a valid phantom-token, capture the full request template
  (URL + POST body) that the page fires, then replay it from *inside* the page context via
  `page.evaluate(fetch(...))`, changing only `search.hotelId` per hotel. The browser JS
  regenerates the token per request, so it works for every hotel. Measured ~0.8s/hotel,
  100% success serially. Concurrent Promise.all triggers anti-bot and returns empty —
  so requests MUST be serial per browser instance.

  Multiple browser instances (config `api_workers`) can run in parallel, each with its own
  page, to scale throughput without concurrent races inside a single page.
"""

from __future__ import annotations

import json
import threading
import time
from pathlib import Path
from typing import Any

from curl_cffi import requests as cffi_requests

from ctrip_hotel.config import ROOT
from ctrip_hotel.http_session import session_post
from ctrip_hotel.session_store import load_storage_state, save_storage_state
from ctrip_hotel.warmup_gate import (
    DOMESTIC_PLAYBOOK,
    classify_domestic_probe,
    final_probe_error,
    print_probe_diagnosis,
)

# ---------------------------------------------------------------------------
# Hotel list — pure HTTP (no browser needed)
# ---------------------------------------------------------------------------

_LIST_URL = "https://m.ctrip.com/restapi/soa2/31454/fetchHotelList"
_ROOM_URL = "https://m.ctrip.com/restapi/soa2/33278/getHotelRoomListInland"


def _domestic_room_ok(payload: dict[str, Any] | None, *, token: str = "") -> tuple[bool, str]:
    """Return (ok, detail) for a getHotelRoomListInland payload."""
    reason, detail = classify_domestic_probe(payload, token=token)
    return reason == "ok", detail


def extract_proxy_pool(cfg: dict[str, Any]) -> list[str]:
    """Build a list of proxy URLs from config.

    Sources (first non-empty wins):
      1. `proxy_list` (list of "ip:port" / "http://ip:port")
      2. `proxy` (single)
      3. `proxy_api_url` — a JSON API that returns {"obj": [{"ip":..,"port":..}]}
    """
    out: list[str] = []
    for p in cfg.get("proxy_list") or []:
        s = str(p).strip()
        if s and s not in out:
            out.append(s if "://" in s else f"http://{s}")
    single = cfg.get("proxy")
    if single:
        s = str(single).strip()
        if s and s not in out:
            out.append(s if "://" in s else f"http://{s}")
    api_url = cfg.get("proxy_api_url")
    if api_url and not out:
        try:
            import urllib.request
            raw = urllib.request.urlopen(str(api_url), timeout=15).read()
            data = json.loads(raw)
            for item in data.get("obj") or []:
                ip, port = item.get("ip"), item.get("port")
                if ip and port:
                    u = f"http://{ip}:{port}"
                    if u not in out:
                        out.append(u)
        except Exception as e:
            print(f"  [proxy] 提取代理失败: {e}")
    return out

MOBILE_UA = (
    "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1"
)

_LIST_HEAD = {
    "platform": "H5",
    "group": "ctrip",
    "cid": "hotel",
    "ctok": "",
    "cver": "1.0",
    "lang": "01",
    "sid": "0000",
    "syscode": "09",
    "auth": "",
    "extension": [],
}


def fetch_hotel_list_pure(
    *,
    city_id: int,
    check_in: str,
    check_out: str,
    pages: int = 1,
    page_size: int = 20,
    delay_ms: int = 0,
    on_page: Any = None,
    proxy: str | None = None,
    proxies: list[str] | None = None,
    max_items: int | None = None,
) -> list[dict[str, Any]]:
    """Fetch hotel catalog via pure HTTP (curl_cffi impersonate=chrome).

    `proxy` is a single proxy URL like "http://ip:port".
    `proxies` is a list of proxy URLs; requests rotate through them per page.
    `max_items`: stop paging once enough raw list items are collected.
    """
    headers = {
        "User-Agent": MOBILE_UA,
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "zh-CN,zh;q=0.9",
        "Content-Type": "application/json",
        "Referer": "https://m.ctrip.com/webapp/hotel/hotellist",
        "Origin": "https://m.ctrip.com",
    }
    proxy_pool = list(proxies or [])
    if proxy:
        proxy_pool.append(proxy)
    all_items: list[dict[str, Any]] = []
    t_list = time.time()
    need = int(max_items) if max_items else 0
    for page_idx in range(1, int(pages or 1) + 1):
        body = {
            "head": _LIST_HEAD,
            "destination": {"type": 2, "geo": {"cityId": int(city_id)}},
            "checkIn": check_in,
            "checkOut": check_out,
            "paging": {"pageIndex": page_idx, "pageSize": int(page_size)},
        }
        proxy_url = proxy_pool[(page_idx - 1) % len(proxy_pool)] if proxy_pool else None
        try:
            proxies = (
                {"http": proxy_url, "https": proxy_url} if proxy_url else None
            )
            r = session_post(
                _LIST_URL,
                json=body,
                headers=headers,
                proxies=proxies,
                impersonate="chrome",
                timeout=20,
                tag="api_list",
            )
            j = r.json()
        except Exception as e:
            print(f"  [list] page {page_idx} error: {e}")
            break
        data = j.get("data") or {}
        items = data.get("hotelList") or []
        if not items:
            break
        all_items.extend(items)
        if on_page:
            on_page(items, page_idx)
        if need and len(all_items) >= need:
            break
        if page_idx < int(pages or 1) and delay_ms:
            time.sleep(delay_ms / 1000.0)
        # Ctrip caps pageSize ~20; stop if fewer than requested (last page).
        if len(items) < int(page_size):
            break
    print(
        f"  [list] {len(all_items)} items / {page_idx} page(s) "
        f"{time.time() - t_list:.1f}s",
        flush=True,
    )
    return all_items


# ---------------------------------------------------------------------------
# Room status — single headless browser page + in-page fetch replay
# ---------------------------------------------------------------------------

_ROOM_TEMPLATE_SCRIPT = """
() => {
  const tpl = window.__CTRIP_ROOM_TEMPLATE__;
  if (!tpl) return null;
  return {
    url: tpl.url,
    post: tpl.post,
    hasTemplate: true,
  };
}
"""

_FETCH_ROOM_SCRIPT = """
async (args) => {
  const {url, post, hotelId} = args;
  const resp = await fetch(url, {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: post,
    credentials: 'include',
  });
  const j = await resp.json();
  return j;
}
"""


class ApiRoomClient:
    """One headless browser page that produces valid phantom-tokens.

    Use `fetch_room(hotel_id)` repeatedly (serial) to get full room status.
    """

    def __init__(
        self,
        cfg: dict[str, Any],
        *,
        worker_id: int | None = None,
        seed_hotel_id: int | str | None = None,
    ) -> None:
        self.cfg = cfg
        self.worker_id = worker_id
        self.seed_hotel_id = seed_hotel_id
        self._pw = None
        self._browser = None
        self._context = None
        self._page = None
        self._template: dict[str, Any] | None = None
        self._album_template: dict[str, Any] | None = None
        self._additional_template: dict[str, Any] | None = None
        self._cookies: str = ""
        self._ready: bool = False
        self._ready_detail: str = ""
        self._session_channel = "api_domestic"

    # -- lifecycle ---------------------------------------------------------

    def __enter__(self) -> "ApiRoomClient":
        from playwright.sync_api import sync_playwright

        self._pw = sync_playwright().start()
        # API mode is headless by default; set api_headed=true (or pass
        # --headed) only to manually pass a one-time captcha during warmup.
        headed = bool(self.cfg.get("api_headed", self.cfg.get("headed", False)))
        launch_kwargs: dict[str, Any] = {
            "headless": not headed,
            "args": [
                "--disable-dev-shm-usage",
                "--disable-extensions",
                "--disable-background-networking",
            ],
        }
        # Prefer bundled Chromium for domestic API so it does not fight headed
        # Edge used by intl signer (intl_browser_channel / browser_channel).
        channel = (
            self.cfg.get("api_browser_channel")
            if "api_browser_channel" in self.cfg
            else ""
        )
        if channel is None:
            channel = ""
        channel = str(channel).lower()
        if channel in {"msedge", "chrome"}:
            try:
                self._browser = self._pw.chromium.launch(
                    channel=channel, **launch_kwargs
                )
            except Exception:
                self._browser = self._pw.chromium.launch(**launch_kwargs)
        else:
            self._browser = self._pw.chromium.launch(**launch_kwargs)
        # H5 detail page fires album/additional more reliably on a phone UA.
        context_kwargs: dict[str, Any] = {
            "locale": "zh-CN",
            "viewport": {"width": 390, "height": 844},
            "user_agent": MOBILE_UA,
            "is_mobile": True,
            "has_touch": True,
        }
        proxy = self.cfg.get("proxy") or self.cfg.get("browser_proxy")
        if proxy:
            context_kwargs["proxy"] = {"server": str(proxy)}
        # Reuse cookies/localStorage from last successful run (Playwright storage_state).
        max_age = int(self.cfg.get("session_max_age_sec") or 6 * 3600)
        state_path = load_storage_state(self._session_channel, max_age_sec=max_age)
        if state_path is not None:
            context_kwargs["storage_state"] = str(state_path)
        ctx = self._browser.new_context(**context_kwargs)
        self._context = ctx
        self._page = ctx.new_page()
        self._page.add_init_script(
            """
            Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
            window.chrome = window.chrome || { runtime: {} };
            """
        )
        # Capture template, then LIVE probe — batch must not start until probe passes.
        self._warmup()
        self._ensure_ready()
        return self

    def is_ready(self) -> bool:
        return bool(self._ready and self._template)

    def _probe_seed_ids(self) -> list[Any]:
        seeds: list[Any] = []
        if self.seed_hotel_id is not None:
            seeds.append(self.seed_hotel_id)
        cfg_seed = self.cfg.get("seed_hotel_id")
        if cfg_seed:
            seeds.append(cfg_seed)
        for x in self.cfg.get("seed_hotel_ids") or []:
            if str(x).isdigit():
                seeds.append(int(x))
        try:
            body = json.loads((self._template or {}).get("post") or "{}")
            hid = (body.get("search") or {}).get("hotelId")
            if hid:
                seeds.insert(0, hid)
        except Exception:
            pass
        # dedupe preserve order
        out: list[Any] = []
        seen: set[str] = set()
        for s in seeds:
            k = str(s)
            if k not in seen:
                seen.add(k)
                out.append(s)
        return out or [1]

    def _ensure_ready(self) -> None:
        """Hard gate: diagnose → auto-fix → only then allow batch."""
        if not self._template:
            raise final_probe_error(
                channel="api",
                reason="template_missing",
                detail="room template missing",
                hotel_id=self.seed_hotel_id,
                tried=[],
            )

        seeds = self._probe_seed_ids()
        seed_idx = 0
        probe_id = seeds[seed_idx]
        attempts = max(int(self.cfg.get("warmup_probe_retries") or 4), 1)
        last_reason, last_detail = "empty", ""
        tried: list[str] = []

        for i in range(attempts):
            token = (self._template.get("headers") or {}).get("phantom-token") or ""
            if not str(token).strip():
                reason, detail = "empty_token", "phantom-token empty"
                _, action, hint = DOMESTIC_PLAYBOOK[reason]
                print_probe_diagnosis(
                    channel="api",
                    reason=reason,
                    detail=detail,
                    action=f"执行 {action}: 重新捕获页面模板",
                    hint=hint,
                    attempt=i + 1,
                    attempts=attempts,
                    hotel_id=probe_id,
                )
                tried.append(f"{reason}:recapture")
                last_reason, last_detail = reason, detail
                if self._page is None:
                    break
                try:
                    self.seed_hotel_id = seeds[min(seed_idx, len(seeds) - 1)]
                    self._warmup()
                except Exception as e:
                    last_detail = f"{detail}; recapture={e}"
                continue

            payload = self.fetch_room(probe_id)
            reason, detail = classify_domestic_probe(payload, token=token)
            if reason == "ok":
                self._ready = True
                self._ready_detail = detail
                print(
                    f"  [api] probe ok ({i + 1}/{attempts}): hotel={probe_id} {detail}",
                    flush=True,
                )
                # Persist browser state for next run (hybrid: browser once tax amortized).
                if self._context is not None:
                    save_storage_state(
                        self._session_channel,
                        self._context,
                        extra={"probe_hotel": probe_id, "detail": detail},
                    )
                if self._album_template and self._additional_template:
                    self.release_browser()
                return

            _, action, hint = DOMESTIC_PLAYBOOK.get(
                reason, (reason, "backoff", "查看日志")
            )
            fix_desc = {
                "recapture": "重新预热捕获 token",
                "next_seed": f"换探针酒店 → {seeds[min(seed_idx + 1, len(seeds) - 1)]}",
                "backoff": "短暂退避后重试",
            }.get(action, action)
            print_probe_diagnosis(
                channel="api",
                reason=reason,
                detail=detail,
                action=f"执行 {action}: {fix_desc}",
                hint=hint,
                attempt=i + 1,
                attempts=attempts,
                hotel_id=probe_id,
            )
            last_reason, last_detail = reason, detail

            if action == "next_seed" and seed_idx + 1 < len(seeds):
                seed_idx += 1
                probe_id = seeds[seed_idx]
                tried.append(f"{reason}:next_seed:{probe_id}")
                continue
            if action == "recapture":
                tried.append(f"{reason}:recapture")
                if self._page is None:
                    break
                try:
                    if seed_idx + 1 < len(seeds):
                        seed_idx += 1
                        self.seed_hotel_id = seeds[seed_idx]
                        probe_id = seeds[seed_idx]
                    self._warmup()
                except Exception as e:
                    last_detail = f"{detail}; recapture={e}"
                continue
            # backoff
            tried.append(f"{reason}:backoff")
            time.sleep(0.5 * (i + 1))

        self._ready = False
        raise final_probe_error(
            channel="api",
            reason=last_reason,
            detail=last_detail,
            hotel_id=probe_id,
            tried=tried,
        )

    # -- warmup ------------------------------------------------------------

    def _warmup(self) -> None:
        """Navigate to a hotel detail page so the page JS emits a room request.

        We capture the request (URL + POST body) that the page fires, and stash it
        on window.__CTRIP_ROOM_TEMPLATE__ for reuse.
        """
        assert self._page is not None
        seed = self.seed_hotel_id
        if seed is None:
            seed = int(self.cfg.get("seed_hotel_id") or 0) or 1
        # Try a few seed hotels in case the page does not fire the room API
        # (anti-bot can be flaky). Reuses the same page across attempts.
        seed_ids = [seed]
        extras = self.cfg.get("seed_hotel_ids") or []
        seed_ids.extend(int(x) for x in extras if str(x).isdigit())

        captured: dict[str, Any] = {}

        # Capture via fetch hook + Playwright request events (XHR may bypass fetch).
        self._page.add_init_script(
            """
            window.__CTRIP_CAPTURED__ = window.__CTRIP_CAPTURED__ || {};
            const origFetch = window.fetch;
            window.fetch = function(...args) {
                try {
                    const [url, opts] = args;
                    const u = String(url);
                    const post = opts ? String(opts.body || '') : '';
                    let headers = {};
                    try {
                        if (opts && opts.headers) headers = JSON.parse(JSON.stringify(opts.headers));
                    } catch (e) {}
                    if (u.includes('getHotelRoomListInland')) {
                        window.__CTRIP_CAPTURED__.room = { url: u, post, headers };
                    } else if (u.toLowerCase().includes('gethotelalbumpicture') || u.toLowerCase().includes('ctgethotelalbum')) {
                        if (!window.__CTRIP_CAPTURED__.album) {
                            window.__CTRIP_CAPTURED__.album = { url: u, post, headers };
                        }
                    } else if (u.toLowerCase().includes('getdetailadditionalinfo')) {
                        if (!window.__CTRIP_CAPTURED__.additional) {
                            window.__CTRIP_CAPTURED__.additional = { url: u, post, headers };
                        }
                    }
                } catch(e) {}
                return origFetch.apply(this, args);
            };
            """
        )

        def _on_request(req) -> None:
            u = req.url or ""
            ul = u.lower()
            try:
                post = req.post_data or ""
            except Exception:
                post = ""
            if "gethotelroomlistinland" in ul and "room" not in captured:
                captured["room"] = {
                    "url": u,
                    "post": post,
                    "headers": dict(req.headers),
                }
            elif (
                "gethotelalbumpicture" in ul or "ctgethotelalbum" in ul
            ) and "album" not in captured:
                captured["album"] = {"url": u, "post": post}
            elif "getdetailadditionalinfo" in ul and "additional" not in captured:
                captured["additional"] = {"url": u, "post": post}

        self._page.on("request", _on_request)

        def _block_heavy(route) -> None:
            try:
                rtype = (route.request.resource_type or "").lower()
                if rtype in {"image", "media", "font", "stylesheet", "texttrack"}:
                    route.abort()
                else:
                    route.continue_()
            except Exception:
                # Route may already be settled when page closes mid-warmup.
                pass

        try:
            self._page.route("**/*", _block_heavy)
        except Exception:
            pass

        t_warm = time.time()
        for i, sid in enumerate(seed_ids):
            url = (
                f"https://m.ctrip.com/webapp/hotel/hoteldetail/{sid}.html"
                f"?checkIn={self.cfg['check_in']}&checkOut={self.cfg['check_out']}"
            )
            print(f"  [api] warmup attempt {i + 1}/{len(seed_ids)}: seed={sid}")
            # Keep network-captured room if any; clear JS bag for this navigation.
            try:
                self._page.evaluate("() => { window.__CTRIP_CAPTURED__ = {}; }")
            except Exception:
                pass
            try:
                self._page.goto(url, timeout=45000, wait_until="domcontentloaded")
            except Exception as e:
                print(f"  [warmup] goto warning: {e}")
            # Wait for room API; keep scrolling so album/additional lazy-load too.
            deadline = time.time() + 16
            while time.time() < deadline:
                try:
                    cap = self._page.evaluate("() => window.__CTRIP_CAPTURED__ || {}")
                except Exception:
                    cap = {}
                if cap.get("room") and "room" not in captured:
                    captured["room"] = cap["room"]
                if cap.get("album"):
                    captured["album"] = cap["album"]
                if cap.get("additional"):
                    captured["additional"] = cap["additional"]
                if captured.get("room") and captured.get("additional"):
                    # album is optional — room browse images usually cover gaps
                    break
                self._page.wait_for_timeout(200)
                if time.time() < deadline:
                    try:
                        self._page.mouse.wheel(0, 1800)
                    except Exception:
                        pass
            if "room" in captured:
                # Extra scroll window for additional if still missing.
                if "additional" not in captured:
                    extra_deadline = time.time() + 6
                    while time.time() < extra_deadline and "additional" not in captured:
                        try:
                            cap = self._page.evaluate(
                                "() => window.__CTRIP_CAPTURED__ || {}"
                            )
                        except Exception:
                            cap = {}
                        if cap.get("additional"):
                            captured["additional"] = cap["additional"]
                        if cap.get("album"):
                            captured["album"] = cap["album"]
                        self._page.wait_for_timeout(200)
                        try:
                            self._page.mouse.wheel(0, 1800)
                        except Exception:
                            pass
                break
        print(f"  [api] capture phase {time.time() - t_warm:.1f}s", flush=True)

        if "room" not in captured:
            raise RuntimeError(
                "warmup failed: 未捕获到房态请求模板。常见原因：当前网络/IP 触发临时风控。"
                "可稍等几分钟重试，或设置 headed=true 手动打开窗口过一次人机验证，"
                "或换 seed_hotel_id / seed_hotel_ids。"
            )
        # Stash templates on window for later evaluate() calls.
        self._page.evaluate(
            """(tpl) => { window.__CTRIP_ROOM_TEMPLATE__ = tpl; }""",
            {"url": captured["room"]["url"], "post": captured["room"]["post"]},
        )
        self._template = captured["room"]
        self._album_template = captured.get("album")
        self._additional_template = captured.get("additional")
        # Capture cookies from the browser context for pure-HTTP replays.
        try:
            self._cookies = "; ".join(
                f"{c['name']}={c['value']}" for c in self._page.context.cookies()
            )
        except Exception:
            self._cookies = ""
        print(
            f"  [api] warmup capture ok: room={'Y' if self._template else 'N'} "
            f"album={'Y' if self._album_template else 'N'} "
            f"additional={'Y' if self._additional_template else 'N'}"
        )
        # Browser is released only after _ensure_ready() probe passes.

    def release_browser(self) -> None:
        """Close Playwright; keep captured templates/cookies for HTTP reuse."""
        # Unroute first — closing with active route handlers spams CancelledError.
        try:
            if self._page is not None:
                self._page.unroute("**/*")
        except Exception:
            pass
        try:
            if self._browser:
                self._browser.close()
        except Exception:
            pass
        self._browser = None
        self._context = None
        self._page = None
        try:
            if self._pw:
                self._pw.stop()
        except Exception:
            pass
        self._pw = None
        ev = self.cfg.get("_api_browser_released")
        if ev is not None:
            try:
                ev.set()
            except Exception:
                pass

    def __exit__(self, exc_type, exc, tb) -> None:
        self.release_browser()

    def _room_headers(self) -> dict[str, str]:
        """Build headers for pure-HTTP room requests from the captured template."""
        hdrs = self._template.get("headers") or {}
        base = {
            "User-Agent": hdrs.get("user-agent")
            or "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15",
            "Accept": "application/json, text/plain, */*",
            "Accept-Language": "zh-CN,zh;q=0.9",
            "Content-Type": "application/json",
            "Referer": hdrs.get("referer") or "https://m.ctrip.com/webapp/hotel/hoteldetail",
            "Origin": "https://m.ctrip.com",
            "phantom-token": hdrs.get("phantom-token") or "",
            "cookie": self._cookies or "",
        }
        # Carry the anti-bot context headers that the page sets.
        for k in (
            "x-ctx-wclient-req",
            "x-ctx-ubt-pageid",
            "x-ctx-ubt-vid",
            "x-ctx-ubt-sid",
            "x-ctx-ubt-pvid",
            "cookieorigin",
            "w-payload-source",
        ):
            v = hdrs.get(k)
            if v:
                base[k] = v
        return base

    def fetch_room(self, hotel_id: int | str) -> dict[str, Any]:
        """Fetch full room status for one hotel via pure HTTP (token reuse)."""
        if self._template is None:
            raise RuntimeError("client not warmed up: room template missing")
        try:
            body = json.loads(self._template["post"])
            body["search"]["hotelId"] = int(hotel_id)
        except Exception:
            body = {"search": {"hotelId": int(hotel_id)}}
        try:
            r = session_post(
                self._template["url"],
                json=body,
                headers=self._room_headers(),
                impersonate="chrome",
                timeout=20,
                tag="api_room",
            )
            j = r.json()
        except Exception as e:
            return {"error": str(e), "data": {}}
        if not isinstance(j, dict):
            return {"error": "non-json response", "data": {}}
        return j

    def fetch_room_batch(
        self,
        hotel_ids: list[int | str],
        *,
        max_workers: int = 8,
    ) -> list[dict[str, Any]]:
        """Fetch rooms for many hotels with a thread pool (pure HTTP)."""
        if not self.is_ready():
            raise RuntimeError(
                "拒绝批量抓取：API 预热探针未通过 "
                f"(ready={self._ready}, detail={self._ready_detail!r})"
            )
        if max_workers <= 1:
            out = []
            for hid in hotel_ids:
                try:
                    out.append(self.fetch_room(hid))
                except Exception as e:
                    out.append({"error": str(e), "data": {}})
                time.sleep(float(self.cfg.get("delay_ms") or 0) / 1000.0)
            return out
        from concurrent.futures import ThreadPoolExecutor, as_completed

        results: dict[int | str, dict[str, Any]] = {}
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            futs = {ex.submit(self.fetch_room, hid): hid for hid in hotel_ids}
            for fut in as_completed(futs):
                hid = futs[fut]
                try:
                    results[hid] = fut.result()
                except Exception as e:
                    results[hid] = {"error": str(e), "data": {}}
        return [results[hid] for hid in hotel_ids]

    # -- album / additional -------------------------------------------------

    def _enrich_body(self, kind: str, template: dict[str, Any], hotel_id: int | str) -> str:
        post = template.get("post") or ""
        try:
            body = json.loads(post)
            if kind == "album":
                if "HotelID" in body:
                    body["HotelID"] = int(hotel_id)
                elif "hotelId" in body:
                    body["hotelId"] = int(hotel_id)
            elif kind == "additional":
                if body.get("queryInfo") is not None:
                    body["queryInfo"]["hotelId"] = int(hotel_id)
            return json.dumps(body)
        except Exception:
            return post

    def _fetch_enrich_http(
        self, kind: str, template: dict[str, Any], hotel_id: int | str
    ) -> dict[str, Any]:
        """Pure-HTTP album/additional using room session phantom-token + cookies."""
        url = template.get("url") or ""
        if not url:
            return {}
        payload = self._enrich_body(kind, template, hotel_id)
        try:
            r = session_post(
                url,
                data=payload.encode("utf-8") if isinstance(payload, str) else payload,
                headers=self._room_headers(),
                impersonate="chrome",
                timeout=20,
                tag="api_enrich",
            )
            j = r.json()
        except Exception as e:
            return {"error": str(e)}
        return j if isinstance(j, dict) else {}

    def fetch_album(self, hotel_id: int | str) -> dict[str, Any]:
        """Fetch hotel gallery; prefer HTTP, fall back to in-page replay."""
        if not self._album_template:
            return {}
        http = self._fetch_enrich_http("album", self._album_template, hotel_id)
        if http and not http.get("error") and (
            http.get("data") or http.get("AlbumCategoryList") or http.get("ResponseStatus")
        ):
            return http
        if self._page is None:
            return http or {}
        return self._replay("album", self._album_template, hotel_id)

    def fetch_additional(self, hotel_id: int | str) -> dict[str, Any]:
        """Fetch POI/nearby; prefer HTTP, fall back to in-page replay."""
        if not self._additional_template:
            return {}
        http = self._fetch_enrich_http("additional", self._additional_template, hotel_id)
        if http and not http.get("error") and (
            http.get("data") or http.get("ResponseStatus")
        ):
            return http
        if self._page is None:
            return http or {}
        return self._replay("additional", self._additional_template, hotel_id)

    def fetch_enrich_batch(
        self,
        hotel_ids: list[int | str],
        *,
        max_workers: int = 8,
    ) -> dict[Any, tuple[dict[str, Any], dict[str, Any]]]:
        """Parallel album+additional via HTTP (stable fallback to serial page replay)."""
        out: dict[Any, tuple[dict[str, Any], dict[str, Any]]] = {
            hid: ({}, {}) for hid in hotel_ids
        }
        if not self._album_template and not self._additional_template:
            return out

        def _http_ok_album(p: dict[str, Any]) -> bool:
            return bool(p) and not p.get("error") and bool(
                p.get("data") or p.get("AlbumCategoryList")
            )

        def _http_ok_add(p: dict[str, Any]) -> bool:
            return bool(p) and not p.get("error") and bool(
                p.get("data") or p.get("ResponseStatus")
            )

        def _one(hid: int | str) -> tuple[Any, dict[str, Any], dict[str, Any]]:
            album: dict[str, Any] = {}
            add: dict[str, Any] = {}
            if self._album_template:
                album = self._fetch_enrich_http("album", self._album_template, hid)
            if self._additional_template:
                add = self._fetch_enrich_http(
                    "additional", self._additional_template, hid
                )
            return hid, album, add

        from concurrent.futures import ThreadPoolExecutor, as_completed

        workers = max(min(max_workers, len(hotel_ids) or 1), 1)
        http_results: dict[Any, tuple[dict[str, Any], dict[str, Any]]] = {}
        with ThreadPoolExecutor(max_workers=workers) as ex:
            futs = [ex.submit(_one, hid) for hid in hotel_ids]
            for fut in as_completed(futs):
                hid, album, add = fut.result()
                http_results[hid] = (album, add)

        # Serial page fallback for HTTP misses (Playwright page is not thread-safe).
        fallback_n = 0
        for hid in hotel_ids:
            album, add = http_results.get(hid, ({}, {}))
            if self._album_template and not _http_ok_album(album) and self._page:
                album = self._replay("album", self._album_template, hid)
                fallback_n += 1
            if self._additional_template and not _http_ok_add(add) and self._page:
                add = self._replay("additional", self._additional_template, hid)
                fallback_n += 1
            out[hid] = (
                album if isinstance(album, dict) else {},
                add if isinstance(add, dict) else {},
            )
        if fallback_n:
            print(f"  [api] enrich page-fallback calls={fallback_n}", flush=True)
        return out

    def _replay(
        self,
        kind: str,
        template: dict[str, Any],
        hotel_id: int | str,
    ) -> dict[str, Any]:
        """Replay a captured request inside the page, changing only hotelId."""
        payload = self._enrich_body(kind, template, hotel_id)
        try:
            j = self._page.evaluate(
                """async (args) => {
                    const resp = await fetch(args.url, {
                        method: 'POST',
                        headers: {'Content-Type': 'application/json'},
                        body: args.post,
                        credentials: 'include',
                    });
                    try { return await resp.json(); }
                    catch(e) { return {error: String(e)}; }
                }""",
                {"url": template["url"], "post": payload},
            )
        except Exception as e:
            return {"error": str(e)}
        return j if isinstance(j, dict) else {}


def normalize_list_payloads(
    items: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Convert raw hotelList items into the catalog shape the rest of the code uses.

    Mirrors `normalize_hotels_from_list_api` but works directly on the raw items.
    """
    rows: list[dict[str, Any]] = []
    for item in items:
        info = item.get("hotelInfo") or item
        summary = info.get("summary") or {}
        name_info = info.get("nameInfo") or {}
        star = info.get("hotelStar") or {}
        comment = info.get("commentInfo") or {}
        position = info.get("positionInfo") or {}
        hotel_id = summary.get("hotelId") or info.get("hotelId")
        if not hotel_id:
            continue
        rows.append(
            {
                "hotel_id": hotel_id,
                "name": name_info.get("name") or info.get("name"),
                "en_name": name_info.get("enName"),
                "star": star.get("star"),
                "score": comment.get("commentScore"),
                "comment_count": comment.get("commenterNumber")
                or comment.get("commentCount"),
                "address": position.get("address") or position.get("positionDesc"),
                "zone": position.get("zoneNames") or position.get("areaName"),
            }
        )
    return rows


def images_from_album_picture(album_payload: dict[str, Any]) -> list[str]:
    """Extract image URLs from the `getHotelAlbumPicture` response.

    Structure: data.AlbumCategoryList[].PictureCategoryList[].AlbumPictureList[]
    Each picture has LargeUrl / SmallUrl / OtherUrl / VideoImageUrl.
    2026+: many official slots are video-only (use VideoImageUrl cover);
    user photos often return empty URL fields (anti-scrape) — callers should
    fall back to room browse images / introduction pictures.
    """
    if not album_payload:
        return []
    data = album_payload.get("data") or album_payload
    urls: list[str] = []
    seen: set[str] = set()

    def _ok(u: Any) -> bool:
        if not u or not isinstance(u, str):
            return False
        low = u.lower().strip()
        if not low.startswith("http"):
            return False
        if any(x in low for x in (".mp4", "video-preview", "/videos/")):
            # allow only if it looks like a cover jpg hosted under videos path
            if not any(low.endswith(ext) for ext in (".jpg", ".jpeg", ".png", ".webp")):
                return False
        if "placeholder" in low or "np-pic.png" in low:
            return False
        return True

    def add(u: Any) -> None:
        if not _ok(u) or u in seen:
            return
        seen.add(u)
        urls.append(u)

    for cat in data.get("AlbumCategoryList") or []:
        if not isinstance(cat, dict):
            continue
        for pcat in cat.get("PictureCategoryList") or []:
            if not isinstance(pcat, dict):
                continue
            for pic in pcat.get("AlbumPictureList") or []:
                if not isinstance(pic, dict):
                    continue
                add(
                    pic.get("LargeUrl")
                    or pic.get("OtherUrl")
                    or pic.get("SmallUrl")
                    or pic.get("NewSmallUrl")
                    or pic.get("VideoImageUrl")
                )
                if len(urls) >= 60:
                    break
            if len(urls) >= 60:
                break
        if len(urls) >= 60:
            break
    return urls


def adapt_album_to_legacy(album_payload: dict[str, Any]) -> dict[str, Any]:
    """Wrap getHotelAlbumPicture response into the legacy `hotelTopImage.imgUrlList`
    shape that `normalize.images_from_album` understands."""
    if not album_payload:
        return {}
    urls = images_from_album_picture(album_payload)
    return {
        "data": {
            "hotelTopImage": {
                "total": len(urls),
                "imgUrlList": [{"imgUrl": u} for u in urls],
            }
        }
    }


def build_fetch_result(
    *,
    hotel_id: int | str,
    hotel_meta: dict[str, Any],
    room_payload: dict[str, Any] | None,
    album_payload: dict[str, Any] | None,
    additional_payload: dict[str, Any] | None,
    check_in: str,
    check_out: str,
) -> dict[str, Any]:
    """Assemble an API-mode fetch result compatible with `build_hotel_document`.

    - `api`: the raw getHotelRoomListInland response (source = "api")
    - `album`: adapted to legacy shape
    - `additional`: raw getDetailAdditionalInfo response
    - `page_hotel`: minimal static info from the list meta (name/star/score/address)
    """
    data = (room_payload or {}).get("data") or {}
    source = "api" if data.get("physicRoomMap") else "none"
    page_hotel = {
        "hotel_id": hotel_id,
        "name": hotel_meta.get("name"),
        "star": hotel_meta.get("star"),
        "address": hotel_meta.get("address"),
        "score": hotel_meta.get("score"),
        "review_count": hotel_meta.get("comment_count"),
        "images": [],
    }
    return {
        "source": source,
        "hotel_id": hotel_id,
        "page_hotel": page_hotel,
        "dom_rooms": [],
        "room_detail_extras": [],
        "api": room_payload,
        "album": adapt_album_to_legacy(album_payload),
        "additional": additional_payload,
        "check_in": check_in,
        "check_out": check_out,
    }
